apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: docuscrypt
  namespace: default
spec:
  hosts: 
    - docuscrypt.xyz.abc  # CHANGEME: same domain as ingress-route.yml
  scaleTargetRef:
    name: docuscrypt
    service: docuscrypt-service
    port: 8000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800  # 30 min idle -> scale to zero