apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/trilium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: trilium-data-pv