apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-client
  template:
    metadata:
      labels:
        app: checkmate-client
    spec:
      containers:
        - name: client
          image: ghcr.io/bluewave-labs/checkmate-client:latest
          env:
            - name: UPTIME_APP_API_BASE_URL
              value: "http://checkmate-server:52345/api/v1"
            - name: UPTIME_APP_CLIENT_HOST
              value: "http://checkmate-client"
          ports:
            - containerPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-server
  template:
    metadata:
      labels:
        app: checkmate-server
    spec:
      containers:
        - name: server
          image: ghcr.io/bluewave-labs/checkmate-backend:latest
          env:
            - name: DB_CONNECTION_STRING
              value: "mongodb://mongodb:27017/uptime_db?replicaSet=rs0"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: CLIENT_HOST
              value: "http://checkmate-client"
            - name: JWT_SECRET
              value: "my_secret"
          ports:
            - containerPort: 52345

apiVersion: v1
kind: Service
metadata:
  name: checkmate-client
spec:
  selector:
    app: checkmate-client
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: checkmate-server
spec:
  selector:
    app: checkmate-server
  ports:
    - port: 52345
      targetPort: 52345

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkmate-client-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: checkmate.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkmate-client
                port:
                  number: 80