# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gatus-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/gatus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-config-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: gatus-config-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: twinproduction/gatus:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: gatus-config-pvc
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
  name: gatus-service
spec:
  selector:
    app: gatus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: gatus.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatus-service
                port:
                  number: 8080