# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
 name: grafana-data-pv
spec:
 capacity:
   storage: 20Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 nfs:
   server: nfs.smb.com
   path: /mnt/ssd/hdd/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: grafana-data-pvc
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 20Gi
 volumeName: grafana-data-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: grafana-web
spec:
 replicas: 1
 selector:
   matchLabels:
     app: grafana-web
 template:
   metadata:
     labels:
       app: grafana-web
   spec:
     containers:
       - name: grafana-web
         image: grafana/grafana-enterprise:12.3.2
         ports:
           - containerPort: 3000
         env:
           - name: GF_SERVER_DOMAIN
             value: grafana.xyz.abc
           - name: GF_SERVER_ROOT_URL
             value: http://grafana.xyz.abc
           - name: GF_SERVER_SERVE_FROM_SUB_PATH
             value: "true"
           #- name: GF_PLUGINS_PREINSTALL
           #  value: grafana-clock-panel
         volumeMounts:
           - name: data-volume
             mountPath: /var/lib/grafana
             readOnly: false
     dnsPolicy: "None"
     dnsConfig:
       nameservers:
         - 9.9.9.9
         - 192.192.188.1
     volumes:
       - name: data-volume
         persistentVolumeClaim:
           claimName: grafana-data-pvc
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
 name: grafana-web-service
spec:
 selector:
   app: grafana-web
 ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-web-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: grafana.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-web-service
                port:
                  number: 3000