# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: termix-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/termix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: termix-data-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: termix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: termix
  template:
    metadata:
      labels:
        app: termix
    spec:
      containers:
        - name: termix
          image: ghcr.io/lukegus/termix:release-1.8.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
              readOnly: false
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: termix-data-pvc
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
  name: termix-service
spec:
  selector:
    app: termix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: termix-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - termix.xyz.abc
      secretName: homelab-tls
  rules:
    - host: termix.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: termix-service
                port:
                  number: 8080