# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptimekuma-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/ukuma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: uptimekuma-data-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimekuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
        - name: uptimekuma
          image: louislam/uptime-kuma:2.0.2
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
              readOnly: false
            - name: tz-config
              mountPath: /etc/timezone
              readOnly: true
            - name: lt-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: uptimekuma-data-pvc
        - name: tz-config
          hostPath:
            path: /etc/timezone
            type: File
        - name: lt-config
          hostPath:
            path: /etc/localtime
            type: File
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
  name: uptimekuma-service
spec:
  selector:
    app: uptimekuma
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - uptime.xyz.abc
      secretName: homelab-tls
  rules:
    - host: uptime.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptimekuma-service
                port:
                  number: 3001