apiVersion: v1
kind: Secret
metadata:
  name: hoppscotch-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://hoppscotch:passme@db.server.com:5432/hoppscotch
  DATA_ENCRYPTION_KEY: passme
  WHITELISTED_ORIGINS: https://hoppscotch.xyz.abc,https://api-hoppscotch.xyz.abc,https://admin-hoppscotch.xyz.abc
  VITE_BASE_URL: https://hoppscotch.xyz.abc
  VITE_SHORTCODE_BASE_URL: https://hoppscotch.xyz.abc
  VITE_ADMIN_URL: https://admin-hoppscotch.xyz.abc
  VITE_BACKEND_GQL_URL: https://api-hoppscotch.xyz.abc/graphql
  VITE_BACKEND_WS_URL: wss://api-hoppscotch.xyz.abc/graphql
  VITE_BACKEND_API_URL: https://api-hoppscoth.xyz.abc/v1
  VITE_APP_TOS_LINK: https://docs.hoppscotch.io/support/terms
  VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy
  ENABLE_SUBPATH_BASED_ACCESS: 'false'