apiVersion: v1
kind: PersistentVolume
metadata:
  name: termix-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/termix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: termix-data-pv