apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: igchromium-http
  namespace: default
spec:
  hosts:
    - igchromium.xyz.abc
  scaleTargetRef:
    name: igchromium
    service: igchromium-service
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 3600
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: termpyfilebrowser-follow-igchromium
  namespace: default
spec:
  scaleTargetRef:
    name: termpyfilebrowser
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: kubernetes-workload
      metadata:
        podSelector: app=igchromium
        value: '1'