apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: paperless-web-http
  namespace: default
spec:
  hosts:
    - paperless.xyz.abc
  scaleTargetRef:
    name: paperless-web
    service: paperless-web-service
    port: 8000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 3600