apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd
          ports:
            - containerPort: 4822
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
spec:
  selector:
    app: guacd
  ports:
    - port: 4822
      targetPort: 4822
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-frontend
  template:
    metadata:
      labels:
        app: guacamole-frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: guacamole
          image: guacamole/guacamole
          env:
            - name: GUACD_HOSTNAME
              value: guacd
            - name: POSTGRESQL_DATABASE
              value: guacamole
            - name: POSTGRESQL_HOSTNAME
              value: 123.45.6.70
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: db-password
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: db-user
            - name: POSTGRESQL_AUTO_CREATE_ACCOUNTS
              value: "true"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
spec:
  selector:
    app: guacamole-frontend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
#  ingressClassName: traefik
  rules:
    - host: guacamole.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guacamole-service
                port:
                  number: 80