# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/trilium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: trilium-data-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: triliumnext/trilium:v0.100.0
          ports:
            - containerPort: 8080
          env:
            - name: TRILIUM_DATA_DIR
              value: /home/node/trilium-data
          volumeMounts:
            - name: data-volume
              mountPath: /home/node/trilium-data
              readOnly: false
            - name: tz-config
              mountPath: /etc/timezone
              readOnly: true
            - name: lt-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: trilium-data-pvc
        - name: tz-config
          hostPath:
            path: /etc/timezone
            type: File
        - name: lt-config
          hostPath:
            path: /etc/localtime
            type: File
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
  name: trilium-service
spec:
  selector:
    app: trilium
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trilium-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - trlm.xyz.abc
      secretName: homelab-tls
  rules:
    - host: trlm.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trilium-service
                port:
                  number: 8080