apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: codearm-http
  namespace: default
spec:
  hosts:
    - codearm.xyz.abc
  scaleTargetRef:
    name: codearm
    service: codearm-service
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800