apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: msoffcryptool-web
  namespace: default
spec:
  host: docucrypt.xyz.abc  # CHANGEME: same domain as ingress-route.yml
  scaleTargetRef:
    service: msoffcryptool-web-service
    port: 8000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800  # 30 min idle -> scale to zero