# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeamd-config-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/code/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeamd-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: codeamd-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeamd-workspace-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/code/workspace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeamd-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: codeamd-workspace-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeamd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeamd
  template:
    metadata:
      labels:
        app: codeamd
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: codeamd
          image: linuxserver/code-server
          ports:
            - containerPort: 8443
          env:
            - name: PROXY_DOMAIN
              value: code.xyz.abc
            - name: DEFAULT_WORKSPACE
              value: /workspace
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Asia/Manila
            - name: PASSWORD
              value: 'passme@'
            - name: SUDO_PASSWORD
              value: 'passme!ng@est'
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: false
            - name: workspace-volume
              mountPath: /workspace
              readOnly: false
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: codeamd-config-pvc
        - name: workspace-volume
          persistentVolumeClaim:
            claimName: codeamd-workspace-pvc
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
  name: codeamd-service
spec:
  selector:
    app: codeamd
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeamd-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: code.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeamd-service
                port:
                  number: 8443