apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: chromium-http
  namespace: default
spec:
  hosts:
    - chromium.xyz.abc
  scaleTargetRef:
    name: chromium
    service: chromium-service
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 3600