# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workpage-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
    #- ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/homepage_work/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workpage-config-pvc
spec:
  accessModes:
    - ReadOnlyMany
    #- ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: workpage-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workpage-icons-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/homepage_work/icons
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workpage-icons-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: workpage-icons-pv
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workpage
  template:
    metadata:
      labels:
        app: workpage
    spec:
      containers:
        - name: workpage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: workpage.xyz.abc
            - name: LOG_TARGETS
              value: stdout
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: icons-volume
              mountPath: /app/public/icons
              readOnly: true
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: workpage-config-pvc
        - name: icons-volume
          persistentVolumeClaim:
            claimName: workpage-icons-pvc
---
# ClusterIP Service (internal only, Traefik will route)
apiVersion: v1
kind: Service
metadata:
  name: workpage-service
spec:
  selector:
    app: workpage
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
#---
## Traefik Middleware: strip `/homepage/` prefix
#apiVersion: traefik.io/v1alpha1
#kind: Middleware
#metadata:
#  name: strip-homepage
#spec:
#  stripPrefix:
#    prefixes:
#      - /homepage
---
# Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workpage-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # traefik.ingress.kubernetes.io/router.middlewares: default-strip-homepage@kubernetescrd
spec:
  rules:
    - host: workpage.xyz.abc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workpage-service
                port:
                  number: 3000