apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: subnet-scanner-http
  namespace: default
spec:
  hosts:
    - need-ip.xyz.abc
  scaleTargetRef:
    name: subnet-scanner
    service: subnet-scanner-service
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300