# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issued
spec:
  replicas: 0
  selector:
    matchLabels:
      app: issued
  template:
    metadata:
      labels:
        app: issued
    spec:
      # nodeSelector:
      #   kubernetes.io/arch: amd64
      containers:
        - name: issued
          image: ghcr.io/metalogico/issued:0.1.1
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: config-volume
              mountPath: /app/data
              readOnly: false
            - name: data-volume
              mountPath: /comics
              readOnly: false
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: issued-config-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: issued-data-pvc