# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: issued-config-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/mngrdr/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: issued-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: issued-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: issued-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/mngrdr/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: issued-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: issued-data-pv