apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: issued-http
  namespace: default
spec:
  hosts:
    - issued.xyz.abc
  scaleTargetRef:
    name: issued
    service: issued-service
    port: 8181
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 3600