# Persistent Volumes and Claims
apiVersion: v1
kind: PersistentVolume
metadata:
  name: office-config-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.smb.com
    path: /mnt/ssd/hdd/office/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: office-config-pv